[[project]]
name = "bhw-dc-bot"
desc = "Discord bot for the Ben's-Hardware community"
tags = []
links = [
    { name = "github", url = "https://github.com/Jojodicus/bhw-dc-bot" },
]


[[project]]
name = "xecute"
desc = "Non-bloated alternative to sudo, doas and rdo"
tags = []
links = [
    { name = "github", url = "https://github.com/Jojodicus/xecute" },
]

[[project]]
name = "qr2eascii"
desc = "Generate/convert a QR-code in E-ASCII-art"
tags = []
links = [
    { name = "github", url = "https://github.com/Jojodicus/qr2eascii" },
]
